### PR TITLE
feat: evaluate openai, cohere and google models in CUREv1

### PR DESCRIPTION
**Pull request by dbuades**
As a follow-up to https://github.com/embeddings-benchmark/results/pull/55, this PR evaluates the following models on CUREv1:

  - name: "openai/text-embedding-3-small"
  - name: "openai/text-embedding-3-large"
  - name: "Cohere/Cohere-embed-english-v3.0"
  - name: "Cohere/Cohere-embed-english-light-v3.0"
  - name: "Cohere/Cohere-embed-multilingual-v3.0"
  - name: "Cohere/Cohere-embed-multilingual-light-v3.0"
  - name: "google/text-embedding-005"
  - name: "google/text-multilingual-embedding-002"

These results were obtained using the code from the following two PRs: https://github.com/embeddings-benchmark/mteb/pull/1562 and https://github.com/embeddings-benchmark/mteb/pull/1564.

As a side note, we would like to run these models on the remaining tasks in the MTEB(Medical) benchmark. However, we initially held off due to API cost constraints. Do you have access to credits with these providers that we could use for this purpose? Alternatively, would it be possible for you to run them on your side?

## Checklist

- [x] Run tests locally to make sure nothing is broken using `make test`. 
- [x] Run the results files checker `make pre-push`.

### CODE REVIEW

**Review by Samoed — APPROVED** [review]

**Comment by Samoed** [comment]
@Muennighoff ran OpenAI models. I think he might have some credits left

**Comment by Muennighoff** [comment]
@dbuades I've sent you an API key :)

**Comment by dbuades** [comment]
> Leaderboard 2.0: Missing results embeddings-benchmark/mteb#1571

Well received, thank you! 🥳

**Comment by dbuades** [comment]
@Muennighoff following up on your comment [here](https://github.com/embeddings-benchmark/mteb/pull/1526#issuecomment-2510017613), I assume we are good reusing results from the `MTEB(Medical)` tasks that already have results for revision 1 of the models, correct?
This way, I’d only need to run the openai models on tasks that don’t already have results for revision 1, since by default mteb would rerun the models on all tasks since we are now on revision 2.

**Comment by Muennighoff** [comment]
> @Muennighoff following up on your comment [here](https://github.com/embeddings-benchmark/mteb/pull/1526#issuecomment-2510017613), I assume we are good reusing results from the `MTEB(Medical)` tasks that already have results for revision 1 of the models, correct? This way, I’d only need to run the openai models on tasks that don’t already have results for revision 1, since by default mteb would rerun the models on all tasks since we are now on revision 2.

Yeah no need to rerun results I think!

**Pull request merged**
