### PR TITLE
Add IBM Granite Embedding Model results

### PR DESCRIPTION
**Pull request by aashka-trivedi**
## Checklist

- [x] Run tests locally to make sure nothing is broken using `make test`. 
- [x] Run the results files checker `make pre-push`.

### Adding a model checklist

Ref #  PR [1613](https://github.com/embeddings-benchmark/mteb/pull/1613)

- I have added model implementation to `mteb/models/` [directory](https://github.com/embeddings-benchmark/mteb/tree/main/mteb/models). Instruction to add a model can be found [here](https://github.com/embeddings-benchmark/mteb/blob/main/docs/reproducible_workflow.md)

### CODE REVIEW

**Review by Samoed — APPROVED** [review]

**Comment by aashka-trivedi** [comment]
HI @Samoed -- since this PR has been merged, I do not see the model results on the [Leaderboard](https://huggingface.co/spaces/mteb/leaderboard)- Is there something Ive missed? Thanks!

**Comment by Samoed** [comment]
We're currently developing a new version of the leaderboard that pulls results from the results repository, but it's still under development and requires a restart: [Leaderboard 2.0 Demo](https://huggingface.co/spaces/mteb/leaderboard_2_demo).  

To appear on the 'old' leaderboard, the simplest way is to add your model's results to its model card using `mteb create_meta`.

**Comment by aashka-trivedi** [comment]
Thanks, done-- is there any action needed after modifying the model card metadata?

**Comment by Samoed** [comment]
No, results will appear soon

**Pull request merged**
