### PR TITLE
Addresults

### PR DESCRIPTION
**Pull request by Muennighoff**

### CODE REVIEW

**Comment by KennethEnevoldsen** [comment]
@Muennighoff will you run `make pre-push` to make sure that tests pass.

**Comment by KennethEnevoldsen** [comment]
@Muennighoff seems like a model_meta.json is missing for the large model

```
>               assert meta_file.exists()
E               AssertionError: assert False
E                +  where False = exists()
E                +    where exists = PosixPath('/Users/au561649/Github/mteb_results/results/text-embedding-3-large/text-embedding-3-large/model_meta.json').exists
```

**Comment by Muennighoff** [comment]
Added all MMTEB results for both OpenAI models now and should be ready! Lmk if there are other things to run

**Review by KennethEnevoldsen — APPROVED** [review]

**Comment by KennethEnevoldsen** [comment]
Merging this in for the leaderboard - did a few minor fixes

**Pull request merged**
